__default__:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 1
  partition: debug
  cpus_per_task: 1

process_ncbi_genomes:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

process_gtdb_genomes:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

