__default__:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 1
  partition: debug
  cpus_per_task: 1

download_genomes_ncbi:
  ntasks_per_node: 32
  partition: debug

derep_ncbi:
  ntasks_per_node: 32
  partition: debug

download_gtdb_ncbi:
  ntasks_per_node: 32
  partition: debug

derep_gtdb:
  ntasks_per_node: 32
  partition: debug

masking_ncbi:
  ntasks_per_node: 32
  partition: debug

masking_gtdb:
  ntasks_per_node: 32
  partition: debug

prelim_map_ncbi:
  ntasks_per_node: 32
  partition: debug

prelim_map_gtdb:
  ntasks_per_node: 32
  partition: debug

build_krakendb:
  ntasks_per_node: 32
  partition: debug

ps_build_db:
  ntasks_per_node: 32
  partition: debug

