# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB/Test1"
cdir: "/storage/hdd1/chh/TaxDB/Test1/coarse"
sdir: "/storage/hdd1/chh/TaxDB/Test1/simulation"

# select from which sources to combine the high resolution database
include_ncbi: "yes"
inlcude_gtdb: "yes"
include_checkv: "yes"

# define taxonomic partitions for highres db that were included
library_highres:
  - fungi
  - protozoa
  - plant

# Included UniVec databases
univec: "UniVec_Core"

# Default parameters
threads: 1

# Parameters for building krakendb
krakenbuild_threads: 32

ps_kmer_length:
  #- 35
  - 25

ps_minimizer_length:
  - 23

ps_minimizer_spaces:
  - 4

max_dbsize: 220000000000

kraken_classify_threads: 16

kraken_confidence:
  - 0
  - 0.1

kraken_rtl:
  - 0
  - 0.25

