# Basic dirs
wdir: "/willerslev/users-shared/science-snm-willerslev-bgl956/taxdb-integration"
rdir: "/willerslev/users-shared/science-snm-willerslev-bgl956/TaxDB_v3"

# Default parameters
threads: 1
fread_threads: 64

# DB name (to avoid overwriting output if more than 1 DB is built)
# db_name: "kraken2_highres_pro_db_nolim"
# db_name: "kraken2_coarse_db_sparse"
# db_name: "kraken2_highres_test"
db_name: "kraken2_onestep_db"
