# Basic dirs
wdir: "/vol/cloud/christiane/Repos/taxdb-integration"
rdir: "/vol/cloud/christiane/NCBI_taxdb_integration/Testing4"
# wdir: "/home/chh/Documents/Repos/taxdb-integration"
# rdir: "/home/chh/Documents/Projects/NCBI_taxdb_integration/Testing7"

# Default parameters
threads: 1

# Define wildcard values for NCBI partitions
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other
  - viral

# Parameters for downloading files
download_threads: 16

# Parameters for processing NCBI genomes
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"
assembly_level:
  fungi: "variable"
  invertebrate: "variable"
  plant: "variable"
  protozoa: "variable"
  vertebrate_mammalian: "variable"
  vertebrate_other: "variable"
  viral: "Complete Genome"

# Parameters for processing GTDB genomes
gtdb_link: "https://data.ace.uq.edu.au/public/gtdb/data/releases/latest"

# Parameters for dereplicating genomes
derep_script: "/vol/cloud/christiane/Repos/Metagenomics-Index-Correction/dereplicate_assemblies.py"
derep_threads: 16
derep_lineage:
  fungi: ""
  invertebrate: ""
  plant: "p__Streptophyta"
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""
  viral: ""
derep_threshold_gtdb: 0.01
derep_threshold_ncbi_main:
  fungi: 0.03
  invertebrate: 0.1
  plant: 0.03
  protozoa: 0.03
  vertebrate_mammalian: 0.1
  vertebrate_other: 0.1
  viral: 0.05
derep_threshold_ncbi_sub:
  fungi: 0.03
  invertebrate: 0.1
  plant: 0.1
  protozoa: 0.03
  vertebrate_mammalian: 0.1
  vertebrate_other: 0.1
  viral: 0.05
derep_taxlevel_ncbi_main:
  fungi: 7
  invertebrate: 6
  plant: 7
  protozoa: 7
  vertebrate_mammalian: 6
  vertebrate_other: 6
  viral: 7
derep_taxlevel_ncbi_sub:
  fungi: 7
  invertebrate: 6
  plant: 6
  protozoa: 7
  vertebrate_mammalian: 6
  vertebrate_other: 6
  viral: 7

# Parameters for formatting taxonomy
tax_script: "/vol/cloud/christiane/Repos/Metagenomics-Index-Correction/tax_from_gtdb.py"

# Include UniVec databases
univec: "UniVec_Core"

# Parameters for building krakendb
masking_threads: 32
krakenbuild_threads: 32
kmer_len: 27
minimizer_len: 25
minimizer_spaces: 4

