# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB"

# Default parameters
threads: 1

# number of threads for simple parallel processes
parallel_threads: 128

# select presets for building kraken DB
# allowed options are 
#   "user" (user-supplied table of accessions and species taxids required)
#   "coarse" (sorting DB)
#   "highres_pro" (high resolution DB with only prokaryotes and viruses)
#   "onestep" (high resolution for prokaryotes and viruses, coarse resolution for eukaryotes)
# kraken2_preset: ""
kraken2_preset: "coarse"
# kraken2_preset: "highres_pro"

# location of file with input accessions and taxids for user input
kraken2_custom: ""

# DB name (to avoid overwriting output if more than 1 DB is built)
# db_name: "kraken2_highres_pro_db_nolim"
db_name: "kraken2_coarse_db_mem190"
# db_name: "kraken2_highres_test"

# Include UniVec databases
univec: "UniVec_Core"
# univec: ""
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"

# enable conterminator (only suitable for coarse and onestep presets or similar custom DB selection)
# kingdoms: "prokaryotes,fungi,protists,plants,metazoa"
kingdoms: ""

# maximum memory for conterminator
cmem: "450G"

# Parameters for building krakendb
masking_threads: 128
krakenbuild_threads: 64
kmer_len: 25
minimizer_len: 23
minimizer_spaces: 4
max_dbsize: 190000000000

# additional settings for coarse preset
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

rank_coarse:
  fungi: "family"
  invertebrate: "class"
  plant: "family"
  protozoa: "family"
  vertebrate_mammalian: "class"
  vertebrate_other: "class"

coarse_sublineage:
  fungi: ""
  invertebrate: ""
  plant: "p__Streptophyta"
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

rank_sublineage:
  fungi: "family"
  invertebrate: "class"
  plant: "class"
  protozoa: "family"
  vertebrate_mammalian: "class"
  vertebrate_other: "class"

# the rank selected here for custom genomes should be the highest of the previous selection 
rank_custom: "class"

nmax_coarse: 3

# for quick collect of genomes used to build the DB, also import info about user supplied genomes
# unlike in collect module, "n" is used here to indicate that no additional input should be considered
# this will be streamlined in later revisions of the workflow
custom_ncbi_pre_derep:
  fungi: "n"
  protozoa: "n"
  plant: "n"
  invertebrate: "n"
  vertebrate_mammalian: "n"
  vertebrate_other: "n"
custom_ncbi_post_derep: "/storage/hdd1/chh/Repos/taxdb-integration/assets/TARA_AP_combined_new.txt"

custom_gtdb_pre_derep: "n"
custom_gtdb_post_derep: "n"

custom_checkv_pre_derep: "n"
custom_checkv_post_derep: "n"

