# Basic dirs
wdir: "/vol/cloud/christiane/Repos/taxdb-integration"
rdir: "/vol/cloud/christiane/NCBI_taxdb_integration/Testing4"
# wdir: "/home/chh/Documents/Repos/taxdb-integration"
# rdir: "/home/chh/Documents/Projects/NCBI_taxdb_integration/Testing7"

# Default parameters
threads: 1

# Define wildcard values for NCBI partitions
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

# Parameters for downloading files
download_threads: 16

# Parameters for processing NCBI genomes
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"
assembly_level:
  fungi: "variable"
  invertebrate: "variable"
  plant: "variable"
  protozoa: "variable"
  vertebrate_mammalian: "variable"
  vertebrate_other: "variable"

# Parameters for processing viral genomes (checkV)
checkv_link: "https://portal.nersc.gov/CheckV/checkv-db-v0.6/genome_db"

# Parameters for processing GTDB genomes
gtdb_link: "https://data.ace.uq.edu.au/public/gtdb/data/releases/latest"

# Parameters for dereplicating genomes
derep_threads: 32

derep_lineage_exclude:
  fungi: ""
  invertebrate: ""
  plant: "p__Streptophyta"
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

z_threshold_gtdb: 2
gtdb_derep_chunks: 5

z_threshold_ncbi_main:
  fungi: 2
  invertebrate: 2
  plant: 2
  protozoa: 2
  vertebrate_mammalian: 2
  vertebrate_other: 2
  viral: 2
ncbi_derep_chunks:
  fungi: 10
  invertebrate: 5
  plant: 5
  protozoa: 10
  vertebrate_mammalian: 5
  vertebrate_other: 5
  viral: 10

z_threshold_checkv: 2
checkv_derep_chunks: 5

# Parameters for formatting taxonomy
tax_script: "/vol/cloud/christiane/Repos/Metagenomics-Index-Correction/tax_from_gtdb.py"

# Include UniVec databases
univec: "UniVec_Core"

# Parameters for building krakendb
masking_threads: 32
krakenbuild_threads: 32
kmer_len: 27
minimizer_len: 25
minimizer_spaces: 4

