# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB"

# Default parameters
threads: 1

# DB name (to avoid overwriting output if more than 1 DB is built)
# db_name: "kraken2_highres_pro_db_nolim"
db_name: "kraken2_coarse_db_nolim"
# db_name: "kraken2_highres_test"


