# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB/Test1"
cdir: "/storage/hdd1/chh/TaxDB/Test1/coarse"
sdir: "/storage/hdd1/chh/TaxDB/Test1/simulation"

# select from which sources to combine the high resolution database
include_ncbi: "yes"
inlcude_gtdb: "yes"
include_checkv: "yes"

# define taxonomic partitions for highres db that were included
library_highres:
  - fungi
  - protozoa
  - plant

# Included UniVec databases
univec: "UniVec_Core"

# Default parameters
threads: 1

# Parameters for building krakendb
krakenbuild_threads: 32

ps_kmer_length:
  #- 35
  - 25

ps_minimizer_length:
  - 23

ps_minimizer_spaces:
  - 4

max_dbsize: 
  - 220
  - 190

kraken_classify_threads: 16

kraken_confidence:
  - 0
  - 0.1

kraken_rtl:
  - 0
  - 0.1
  - 0.15
  - 0.2
  - 0.25

# parameters for metagenome simulation
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

random_link: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz"

download_threads: 32

read_length:
  - 150

insert_size: 350

sim_seqdepth: 1e7

sim_threads: 32

short_read_length:
  - 80
  - 40

# manually decide on best paremter settings for coarse DB for sorting
best_coarse_PE: ""
best_coarse_SE: ""

