# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB_v3"

# Default parameters
threads: 1

# Define wildcard values for NCBI partitions
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

library_highres:
  - fungi
  - protozoa
  - plant

# this parameter is only used to specify for which NCBI partitions the genome size should be obtained from the assembly summary
library_coarse:
  - vertebrate_mammalian
  - vertebrate_other
  - invertebrate

# number of threads for simple parallel processes
parallel_threads: 128

# Parameters for downloading files
download_threads: 32
download_onefile: 16

# Parameters for processing NCBI genomes
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"
assembly_level:
  fungi: "variable"
  invertebrate: "variable"
  plant: "variable"
  protozoa: "variable"
  vertebrate_mammalian: "variable"
  vertebrate_other: "variable"

# Parameters for processing viral genomes (checkV)
checkv_link: "https://portal.nersc.gov/CheckV/checkv-db-v0.6-full.tar.gz"

# Parameters for processing GTDB genomes
gtdb_link: "https://data.ace.uq.edu.au/public/gtdb/data/releases/latest"

# Parameters for filtering assemblies based on contig stats
filter_ncbi_fields:
  fungi: "genome_size,gc_avg,ctg_L50"
  protozoa: "genome_size,gc_avg,ctg_L50"
  plant: "genome_size,gc_avg,ctg_L50"
  invertebrate: "genome_size,gc_avg,ctg_L50"
  vertebrate_mammalian: "genome_size,gc_avg,ctg_L50"
  vertebrate_other: "genome_size,gc_avg,ctg_L50"

filter_ncbi_abs:
  fungi: "-1,-1,-1"
  protozoa: "-1,-1,-1"
  plant: "-1,-1,-1"
  invertebrate: "-1,-1,-1"
  vertebrate_mammalian: "-1,-1,-1"
  vertebrate_other: "-1,-1,-1"

filter_ncbi_rel:
  fungi: "0.1,0.1,0.1"
  protozoa: "0.1,0.1,0.1"
  plant: "0.1,0.1,0.1"
  invertebrate: "0.1,0.1,0.1"
  vertebrate_mammalian: "0.1,0.1,0.1"
  vertebrate_other: "0.1,0.1,0.1"

filter_ncbi_dif:
  fungi: "0.1,1,0.25"
  protozoa: "0.1,1,0.25"
  plant: "0.1,1,0.25"
  invertebrate: "0.1,1,0.25"
  vertebrate_mammalian: "0.1,1,0.25"
  vertebrate_other: "0.1,1,0.25"

filter_ncbi_sign:
  fungi: "greater,both,greater"
  protozoa: "greater,both,greater"
  plant: "greater,both,greater"
  invertebrate: "greater,both,greater"
  vertebrate_mammalian: "greater,both,greater"
  vertebrate_other: "greater,both,greater"

# Optional: include custom assemblies
# pre_derep: 4 column table with accession, taxonomic path, location fna, location faa (if available, otherwise NA)
# post_derep: format is the same as for derep metadata output (with header row)
# proteins: 3 column table with accession, taxonomic path, location faa
custom_ncbi_pre_derep:
  fungi: ""
  protozoa: ""
  plant: ""
  invertebrate: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""
custom_ncbi_post_derep: "/storage/hdd1/chh/Repos/taxdb-integration/assets/TARA_AP_combined_v2.txt"

custom_gtdb_pre_derep: ""
custom_gtdb_post_derep: ""

custom_checkv_pre_derep: ""
custom_checkv_post_derep: ""

custom_euk_prot: "/storage/hdd1/chh/Repos/taxdb-integration/assets/EukProt_taxonomy_v2.txt"
custom_pro_prot: ""
custom_vir_prot: ""

# Parameters for dereplicating genomes
derep_threads: 32

derep_lineage_exclude:
  fungi: ""
  invertebrate: ""
  plant: ""
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

z_threshold_gtdb: 2
m_threshold_gtdb: 0.01
gtdb_derep_chunks: 5

z_threshold_ncbi:
  fungi: 2
  plant: 2
  protozoa: 2
  invertebrate: 2
  vertebrate_mammalian: 2
  vertebrate_other: 2

m_threshold_ncbi:
  fungi: 0.01
  plant: 0.01
  protozoa: 0.01
  invertebrate: 0.01
  vertebrate_mammalian: 0.01
  vertebrate_other: 0.01

ncbi_derep_chunks:
  fungi: 5
  plant: 5
  protozoa: 5
  invertebrate: 5
  vertebrate_mammalian: 5
  vertebrate_other: 5

ani_fraglen_ncbi:
  fungi: 0.0005
  plant: 0.0005
  protozoa: 0.0005
  invertebrate: 0.0005
  vertebrate_mammalian: 0.0005
  vertebrate_other: 0.0005

z_threshold_checkv: 2
m_threshold_checkv: 0.01
checkv_derep_chunks: 5

# Parameters for formatting taxonomy
gtdb_to_taxdump: "/storage/hdd1/chh/Repos/gtdb_to_taxdump/gtdb_to_taxdump_mod.py"

# threads to generate accession2taxid
taxmap_threads: 64

# parameters for clustering (dereplicating) proteins
cov: 0.8
cov_mode: 1
min_seq_id: 0.95


