# Basic dirs
wdir: "/willerslev/users-shared-snm-willerslev-bgl956/taxdb-integration"
rdir: "/willerslev/users-shared-snm-willerslev-bgl956/TaxDB_v3"

# Default parameters
threads: 1

# number of threads for simple parallel processes
parallel_threads: 128

# Include UniVec databases (to quickly identify segments within nucleic acid sequences which may be of vector origin)
univec: "UniVec_Core"
# univec: ""
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"

# DB name (to avoid overwriting output if more than 1 DB is built)
db_name: "vanilla" # based on the flavours (see config_DB.yaml)

# enable conterminator (only suitable for coarse and onestep presets or similar custom DB selection)
# kingdoms: "prokaryotes,fungi,protists,plants,metazoa"
kingdoms: ""

# maximum memory for conterminator
cmem: "450G"

# Parameters for building krakendb
masking_threads: 128
krakenbuild_threads: 128
kmer_len: 31
minimizer_len: 27
minimizer_spaces: 6
max_dbsize: 700000000000
