# Basic dirs
wdir: "/willerslev/users-shared-snm-willerslev-bgl956/taxdb-integration"
rdir: "/willerslev/users-shared-snm-willerslev-bgl956/TaxDB_v3"

# Default parameters
threads: 1

# number of threads for building CAT database
parallel_threads: 64

