# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB/Test1"
cdir: "/storage/hdd1/chh/TaxDB/Test1/coarse"

# Default parameters
threads: 1

# Define wildcard values for NCBI partitions
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

library_highres:
  - fungi
  - protozoa
  - plant

# this parameter is only used to specify for which NCBI partitions the genome size should be obtained from the assembly summary
library_coarse:
  - vertebrate_mammalian
  - vertebrate_other
  - invertebrate

# Parameters for downloading files
download_threads: 32
download_onefile: 16

# Parameters for processing NCBI genomes
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"
assembly_level:
  fungi: "variable"
  invertebrate: "variable"
  plant: "variable"
  protozoa: "variable"
  vertebrate_mammalian: "variable"
  vertebrate_other: "variable"

# Parameters for processing viral genomes (checkV)
checkv_link: "https://portal.nersc.gov/CheckV/checkv-db-v0.6-full.tar.gz"

# Parameters for processing GTDB genomes
gtdb_link: "https://data.ace.uq.edu.au/public/gtdb/data/releases/latest"

# Parameters for filtering assemblies based on contig stats (only for highres)
filter_ncbi_fields:
  fungi: "genome_size,gc_avg,ctg_L50"
  protozoa: "genome_size,gc_avg,ctg_L50"
  plant: "genome_size,gc_avg,ctg_L50"

filter_ncbi_abs:
  fungi: "-1,-1,-1"
  protozoa: "-1,-1,-1"
  plant: "-1,-1,-1"

filter_ncbi_rel:
  fungi: "0.1,0.1,0.1"
  protozoa: "0.1,0.1,0.1"
  plant: "0.1,0.1,0.1"

filter_ncbi_dif:
  fungi: "0.1,1,0.25"
  protozoa: "0.1,1,0.25"
  plant: "0.1,1,0.25"

filter_ncbi_sign:
  fungi: "greater,both,greater"
  protozoa: "greater,both,greater"
  plant: "greater,both,greater"

# Optional: include custom assemblies
custom_ncbi:
  fungi: ""
  protozoa: ""
  plant: ""

custom_gtdb: ""

custom_checkv: ""

# Parameters for dereplicating genomes
derep_threads: 32

derep_lineage_exclude:
  fungi: ""
  invertebrate: ""
  plant: "p__Streptophyta"
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

z_threshold_gtdb: 2
m_threshold_gtdb: 0.01
gtdb_derep_chunks: 5

z_threshold_ncbi:
  fungi: 2
  plant: 2
  protozoa: 2
m_threshold_ncbi:
  fungi: 0.01
  plant: 0.01
  protozoa: 0.01
ncbi_derep_chunks:
  fungi: 5
  plant: 5
  protozoa: 5
ani_fraglen_ncbi:
  fungi: 0.0005
  plant: 0.0005
  protozoa: 0.0005

z_threshold_checkv: 2
m_threshold_checkv: 0.01
checkv_derep_chunks: 5

# Parameters for formatting taxonomy
tax_script: "/storage/hdd1/chh/Repos/Metagenomics-Index-Correction/tax_from_gtdb.py"

# Include UniVec databases
univec: "UniVec_Core"

# Parameters for building krakendb
masking_threads: 32
krakenbuild_threads: 32
kmer_len: 31
minimizer_len: 23
minimizer_spaces: 4
max_dbsize: 700000000000

# settings for coarse DB
rank_coarse:
  fungi: "family"
  invertebrate: "class"
  plant: "family"
  protozoa: "family"
  vertebrate_mammalian: "class"
  vertebrate_other: "class"

coarse_sublineage:
  fungi: ""
  invertebrate: ""
  plant: "p__Streptophyta"
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

rank_sublineage:
  fungi: "family"
  invertebrate: "class"
  plant: "class"
  protozoa: "family"
  vertebrate_mammalian: "class"
  vertebrate_other: "class"

nmax_coarse: 3

# maximum memory for conterminator
cmem: "500G"

