# Basic dirs
wdir: "/storage/hdd1/chh/Repos/taxdb-integration"
rdir: "/storage/hdd1/chh/TaxDB_v3"

# Default parameters
threads: 1

# number of threads for simple parallel processes
parallel_threads: 128

# select presets for building kraken DB
# allowed options are 
#   "user" (user-supplied table of accessions and species taxids required)
#   "coarse" (sorting DB)
#   "highres_pro" (high resolution DB with only prokaryotes and viruses)
#   "onestep" (high resolution for prokaryotes and viruses, coarse resolution for eukaryotes)
#   "microeuk" (high resolution for fungi and protists, with representatives of other eukaryotic groups)
# kraken2_preset: "microeuk"
# kraken2_preset: "coarse"
# kraken2_preset: "highres_pro"
kraken2_preset: "onestep"

# location of file with input accessions and taxids for user input
kraken2_custom: ""

# DB name (to avoid overwriting output if more than 1 DB is built)
# db_name: "kraken2_highres_pro_db"
# db_name: "kraken2_coarse_db"
# db_name: "kraken2_highres_test"
# db_name: "kraken2_microeuk_db"
db_name: "kraken2_onestep_db_k31"

# Include UniVec databases
univec: "UniVec_Core"
# univec: ""
ncbi_server: "http://ftp.ncbi.nlm.nih.gov"

# enable conterminator (only suitable for coarse and onestep presets or similar custom DB selection)
# kingdoms: "prokaryotes,fungi,protists,plants,metazoa"
kingdoms: ""

# maximum memory for conterminator
cmem: "450G"

# Parameters for building krakendb
masking_threads: 128
krakenbuild_threads: 128
kmer_len: 31
minimizer_len: 27
minimizer_spaces: 6
max_dbsize: 700000000000


#######################################
# additional settings for coarse preset
# those are the same as for the onestep preset
library_name:
  - fungi
  - invertebrate
  - plant
  - protozoa
  - vertebrate_mammalian
  - vertebrate_other

rank_coarse:
  fungi: "family"
  invertebrate: "phylum" # "class"
  plant: "phylum" # "class" # previously family
  protozoa: "family"
  vertebrate_mammalian: "phylum" # "class"
  vertebrate_other: "phylum" # "class"

coarse_sublineage:
  fungi: ""
  invertebrate: ""
  plant: "" # previously p__Streptophyta
  protozoa: ""
  vertebrate_mammalian: ""
  vertebrate_other: ""

rank_sublineage:
  fungi: "family"
  invertebrate: "phylum"
  plant: "phylum"
  protozoa: "family"
  vertebrate_mammalian: "phylum"
  vertebrate_other: "phylum"

# the rank selected here for custom genomes should be the highest of the previous selection 
rank_custom: "phylum" # "class"

nmax_coarse: 3


#########################################
# additional settings for microeuk preset
library_micro:
  - fungi
  - protozoa

library_macro:
  - invertebrate
  - plant
  #- vertebrate_mammalian
  - vertebrate_other

rank_macro:
  invertebrate: "phylum"
  plant: "phylum"
  #vertebrate_mammalian: "phylum"
  vertebrate_other: "phylum"

macro_sublineage:
  invertebrate: ""
  plant: ""
  vertebrate_other: ""

macro_rank_sublineage:
  invertebrate: "phylum"
  plant: "phylum"
  vertebrate_other: "phylum"

# number of genomes to select per level of rank
nmax_macro: 3



# for quick collect of genomes used to build the DB, also import info about user supplied genomes
# unlike in collect module, "n" is used here to indicate that no additional input should be considered
# this will be streamlined in later revisions of the workflow
custom_ncbi_pre_derep:
  fungi: "n"
  protozoa: "n"
  plant: "n"
  invertebrate: "n"
  vertebrate_mammalian: "n"
  vertebrate_other: "n"
custom_ncbi_post_derep: "/storage/hdd1/chh/Repos/taxdb-integration/assets/euk_custom_nucl.txt"

custom_gtdb_pre_derep: "n"
custom_gtdb_post_derep: "/storage/hdd1/chh/Repos/taxdb-integration/assets/pro_custom_nucl.txt"

custom_checkv_pre_derep: "n"
custom_checkv_post_derep: "/storage/hdd1/chh/Repos/taxdb-integration/assets/vir_custom_nucl.txt"

